marquez:
  replicaCount: 1
  image:
    registry: docker.io
    repository: marquezproject/marquez
    tag: 0.20.0
    pullPolicy: IfNotPresent
  db:
    host: localhost
    port: 5432
    name: marquez
    user: buendia
    password: macondo
  migrateOnStartup: true
  hostname: localhost
  port: 5000
  adminPort: 5001
  resources:
    limits: {}
    requests: {}

web:
  ## Enables creation of the web UI
  ##
  enabled: true
  ## Number of desired replicas
  ##
  replicaCount: 1
  ## Marquez web image version
  ## ref: https://hub.docker.com/r/marquezproject/marquez-web/tags/
  ##
  image:
    registry: docker.io
    repository: marquezproject/marquez-web
    tag: 0.20.0
    pullPolicy: IfNotPresent
  ## Marquez website will run on this port
  ##
  port: 3000
  ## Resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    # Typically best to not specify these settings, unless you've got a specific
    # reason to customize.
    limits: {}
    #    cpu: 200m
    #    memory: 1Gi
    requests: {}
    #    memory: 256Mi
    #    cpu: 250m
